# Generated by Django 4.2.5 on 2023-09-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='aaa', upload_to='gallary'),
            preserve_default=False,
        ),
    ]
